name: CI

on:
  push:
    branches:
      - dev

jobs:
  test:
    name: Run Jest tests
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./client/

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '21.6.0'

      - name: Install dependencies
        run: npm install
        working-directory: ./client/
        
      - name: Run Jest tests
        run: npm run test 
        working-directory: ./client/
